{% set name = "cmiles" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/openforcefield/cmiles/archive/v{{ version }}.tar.gz
  sha256: 3bf76a66361242b66adbecf332071b887143bf82f2ab7a3aabee5e54d7cdad09

build:
  number: 1

outputs:
  - name: cmiles-base
    script: build_base.sh

    requirements:
      host:
        - python >=3.6
        - pip
      run:
        - python >=3.6

    test:
      requires:
        - rdkit
      imports:
        - cmiles

  - name: cmiles
    build:
      noarch: python

    requirements:
      run:
        - rdkit
        - {{ pin_subpackage('cmiles-base', max_pin="x.x.x") }}

    test:
      imports:
        - cmiles

about:
  home: https://github.com/openforcefield/cmiles
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Generate canonical molecule identifiers for quantum chemistry
  doc_url: https://cmiles.readthedocs.io/
  dev_url: https://github.com/openforcefield/cmiles

extra:
  recipe-maintainers:
    - mattwthompson
    - j-wags
    - dotsdl
    - jaimergp
    - jthorton
